/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examen2p2_carlossanabria;

import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP1
 */
public class JF_Examen2 extends javax.swing.JFrame {

    /**
     * Creates new form JF_Examen2
     */
    public JF_Examen2() {
        initComponents();
        DefaultComboBoxModel modelo1= (DefaultComboBoxModel)CB_TipoCarroce.getModel(); 
        modelo1.addElement("Default");
        modelo1.addElement("Familiar");
        modelo1.addElement("SUV");
        modelo1.addElement("Compacto");
        modelo1.addElement("Subcompacto");
        modelo1.addElement("Deportivo");
        CB_TipoCarroce.setModel(modelo1);
        DefaultComboBoxModel modelo2= (DefaultComboBoxModel)CB_TipoMotor.getModel();
        modelo2.addElement("Default");
        modelo2.addElement("Combustion");
        modelo2.addElement("Hibrido");
        modelo2.addElement("Electrico");
        CB_TipoMotor.setModel(modelo2);
        DefaultComboBoxModel modelo3= (DefaultComboBoxModel)CB_Vehiculo.getModel();
        modelo2.addElement("Default");
        modelo2.addElement("Hibrido");
        modelo2.addElement("Electrico");
        CB_Vehiculo.setModel(modelo3);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JD_CRUDVehiculos = new javax.swing.JDialog();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        JT_ListarVehiculos = new javax.swing.JTable();
        JB_ModificarVehiculo = new javax.swing.JButton();
        JB_EliminarVehiculos = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        TF_Marca = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        TF_Modelo = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        TF_VIN = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        CB_TipoCarroce = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        CB_TipoMotor = new javax.swing.JComboBox<>();
        JB_BuscarMotor = new javax.swing.JButton();
        JD_CRUDBateria = new javax.swing.JDialog();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        JT_ListarCarros1 = new javax.swing.JTable();
        JB_ModificarCarro1 = new javax.swing.JButton();
        JB_EliminarCarros1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        TF_Marca1 = new javax.swing.JTextField();
        JS_Capacidad = new javax.swing.JSpinner();
        JS_Autonomia = new javax.swing.JSpinner();
        JS_Modulos = new javax.swing.JSpinner();
        JS_Carga = new javax.swing.JSpinner();
        CB_Vehiculo = new javax.swing.JComboBox<>();
        JS_Tiempo = new javax.swing.JSpinner();
        JB_Bateria = new javax.swing.JButton();
        JD_MenuSimulacion = new javax.swing.JDialog();
        JB_EsamblarBaterias = new javax.swing.JButton();
        JB_GenerarReporteEnsamblaje = new javax.swing.JButton();
        jLabel54 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JL_BateriaEnsamblaje = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        JL_CarrosEnsamblados = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        JD_Ensamblaje = new javax.swing.JDialog();
        jLabel47 = new javax.swing.JLabel();
        JL_BateriaActual = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        JL_CarroActual = new javax.swing.JLabel();
        PB_Ensamblaje = new javax.swing.JProgressBar();
        JB_IniciarEsamblaje = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        JT_SimulacionEnsamblaje = new javax.swing.JTable();
        JD_Combustion = new javax.swing.JDialog();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        JS_Cilidrada = new javax.swing.JSpinner();
        jLabel15 = new javax.swing.JLabel();
        JS_NumCili = new javax.swing.JSpinner();
        jLabel16 = new javax.swing.JLabel();
        JS_Consumo = new javax.swing.JSpinner();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        JB_AgregarVehiculos = new javax.swing.JButton();
        JD_Hibrido = new javax.swing.JDialog();
        JS_Capacidad_m = new javax.swing.JSpinner();
        JS_Cantidad_de_galones = new javax.swing.JSpinner();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        TF_Precio = new javax.swing.JTextField();
        JB_AgregarVehiculos1 = new javax.swing.JButton();
        JD_Electrico = new javax.swing.JDialog();
        JS_Coeficiente = new javax.swing.JSpinner();
        jLabel24 = new javax.swing.JLabel();
        JS_NumMotores = new javax.swing.JSpinner();
        jLabel25 = new javax.swing.JLabel();
        JS_Recarga = new javax.swing.JSpinner();
        JB_AgregarVehiculos2 = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        JM_AdminCarrosBateria = new javax.swing.JMenu();
        JMI_CrudVehiculos = new javax.swing.JMenuItem();
        JMI_CrudBateria = new javax.swing.JMenuItem();
        JM_SimulacionHilo = new javax.swing.JMenu();
        JMI_SimulacionHilo = new javax.swing.JMenuItem();

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel3.setText("Administracion Vehiculos");

        JT_ListarVehiculos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Marca", "VIN", "Modelo", "Tipo de Carroceria"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(JT_ListarVehiculos);

        JB_ModificarVehiculo.setText("Modificar");
        JB_ModificarVehiculo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JB_ModificarVehiculoMouseClicked(evt);
            }
        });

        JB_EliminarVehiculos.setText("Eliminar");
        JB_EliminarVehiculos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JB_EliminarVehiculosMouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("Listar Vehiculos");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setText("Marca: ");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setText("Modelo: ");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel10.setText("VIN:");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel11.setText("Carrocería: ");

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel12.setText("Tipo de Motor: ");

        JB_BuscarMotor.setText("Buscar Motor");
        JB_BuscarMotor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JB_BuscarMotorMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout JD_CRUDVehiculosLayout = new javax.swing.GroupLayout(JD_CRUDVehiculos.getContentPane());
        JD_CRUDVehiculos.getContentPane().setLayout(JD_CRUDVehiculosLayout);
        JD_CRUDVehiculosLayout.setHorizontalGroup(
            JD_CRUDVehiculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JD_CRUDVehiculosLayout.createSequentialGroup()
                .addGap(340, 340, 340)
                .addComponent(jLabel3)
                .addContainerGap(469, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JD_CRUDVehiculosLayout.createSequentialGroup()
                .addGroup(JD_CRUDVehiculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JD_CRUDVehiculosLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(JD_CRUDVehiculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(JD_CRUDVehiculosLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(TF_Marca, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(JD_CRUDVehiculosLayout.createSequentialGroup()
                                .addGroup(JD_CRUDVehiculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(JD_CRUDVehiculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TF_VIN, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TF_Modelo, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(JD_CRUDVehiculosLayout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(18, 18, 18)
                                .addComponent(CB_TipoCarroce, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(JD_CRUDVehiculosLayout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(18, 18, 18)
                                .addComponent(CB_TipoMotor, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(JD_CRUDVehiculosLayout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(JB_BuscarMotor, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(JD_CRUDVehiculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(JD_CRUDVehiculosLayout.createSequentialGroup()
                        .addComponent(JB_ModificarVehiculo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JB_EliminarVehiculos))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 641, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38))
        );
        JD_CRUDVehiculosLayout.setVerticalGroup(
            JD_CRUDVehiculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JD_CRUDVehiculosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(JD_CRUDVehiculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(JD_CRUDVehiculosLayout.createSequentialGroup()
                        .addGroup(JD_CRUDVehiculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(TF_Marca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(JD_CRUDVehiculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(TF_Modelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(JD_CRUDVehiculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(TF_VIN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(JD_CRUDVehiculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(CB_TipoCarroce, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(JD_CRUDVehiculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(CB_TipoMotor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addComponent(JB_BuscarMotor)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JD_CRUDVehiculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JB_EliminarVehiculos)
                    .addComponent(JB_ModificarVehiculo))
                .addGap(55, 55, 55))
        );

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel5.setText("Administracion Baterias");

        JT_ListarCarros1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Marca", "Capacidad Bateria", "Tipo de Vehiculo", "Tiempo de Ensamblaje", "Autonomia", "Capacidad Carga"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane4.setViewportView(JT_ListarCarros1);

        JB_ModificarCarro1.setText("Modificar");
        JB_ModificarCarro1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JB_ModificarCarro1MouseClicked(evt);
            }
        });

        JB_EliminarCarros1.setText("Eliminar");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setText("Listar Bateria");

        jLabel26.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel26.setText("Marca: ");

        jLabel27.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel27.setText("Capacidad: ");

        jLabel30.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel30.setText("Autonomia: ");

        jLabel31.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel31.setText("Cantidad Modulos: ");

        jLabel32.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel32.setText("Tipo Vehiculo: ");

        jLabel33.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel33.setText("Capacidad Carga: ");

        jLabel34.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel34.setText("Tiempo: ");

        JB_Bateria.setText("Agregar Bateria");
        JB_Bateria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JB_BateriaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout JD_CRUDBateriaLayout = new javax.swing.GroupLayout(JD_CRUDBateria.getContentPane());
        JD_CRUDBateria.getContentPane().setLayout(JD_CRUDBateriaLayout);
        JD_CRUDBateriaLayout.setHorizontalGroup(
            JD_CRUDBateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JD_CRUDBateriaLayout.createSequentialGroup()
                .addGap(340, 340, 340)
                .addComponent(jLabel5)
                .addContainerGap(497, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JD_CRUDBateriaLayout.createSequentialGroup()
                .addGroup(JD_CRUDBateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JD_CRUDBateriaLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(JD_CRUDBateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(JD_CRUDBateriaLayout.createSequentialGroup()
                                .addComponent(jLabel26)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(TF_Marca1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(JD_CRUDBateriaLayout.createSequentialGroup()
                                .addComponent(jLabel27)
                                .addGap(18, 18, 18)
                                .addComponent(JS_Capacidad, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(JD_CRUDBateriaLayout.createSequentialGroup()
                                .addComponent(jLabel30)
                                .addGap(18, 18, 18)
                                .addComponent(JS_Autonomia, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(JD_CRUDBateriaLayout.createSequentialGroup()
                                .addComponent(jLabel31)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JS_Modulos, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(JD_CRUDBateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, JD_CRUDBateriaLayout.createSequentialGroup()
                                    .addComponent(jLabel34)
                                    .addGap(94, 94, 94)
                                    .addComponent(JS_Tiempo, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, JD_CRUDBateriaLayout.createSequentialGroup()
                                    .addGroup(JD_CRUDBateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel33)
                                        .addComponent(jLabel32))
                                    .addGap(18, 18, 18)
                                    .addGroup(JD_CRUDBateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(JS_Carga, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                                        .addComponent(CB_Vehiculo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                        .addGap(142, 142, 142))
                    .addGroup(JD_CRUDBateriaLayout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(JB_Bateria, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(JD_CRUDBateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(JD_CRUDBateriaLayout.createSequentialGroup()
                        .addComponent(JB_ModificarCarro1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JB_EliminarCarros1))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 641, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38))
        );
        JD_CRUDBateriaLayout.setVerticalGroup(
            JD_CRUDBateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JD_CRUDBateriaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(JD_CRUDBateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(JD_CRUDBateriaLayout.createSequentialGroup()
                        .addGroup(JD_CRUDBateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel26)
                            .addComponent(TF_Marca1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(JD_CRUDBateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel27)
                            .addComponent(JS_Capacidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(JD_CRUDBateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel30)
                            .addComponent(JS_Autonomia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(JD_CRUDBateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel31)
                            .addComponent(JS_Modulos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(JD_CRUDBateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel33)
                            .addComponent(JS_Carga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(JD_CRUDBateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel32)
                            .addComponent(CB_Vehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(JD_CRUDBateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel34)
                            .addComponent(JS_Tiempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addComponent(JB_Bateria)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JD_CRUDBateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JB_EliminarCarros1)
                    .addComponent(JB_ModificarCarro1))
                .addGap(55, 55, 55))
        );

        JB_EsamblarBaterias.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        JB_EsamblarBaterias.setText("Ensamblar Baterias");
        JB_EsamblarBaterias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JB_EsamblarBateriasMouseClicked(evt);
            }
        });

        JB_GenerarReporteEnsamblaje.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        JB_GenerarReporteEnsamblaje.setText("Generar Reporte");
        JB_GenerarReporteEnsamblaje.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JB_GenerarReporteEnsamblajeMouseClicked(evt);
            }
        });

        jLabel54.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        jLabel54.setText("recuerde seleccionar ambas listas para el ensamblaje");

        JL_BateriaEnsamblaje.setModel(new DefaultListModel());
        jScrollPane1.setViewportView(JL_BateriaEnsamblaje);

        JL_CarrosEnsamblados.setModel(new DefaultListModel());
        jScrollPane2.setViewportView(JL_CarrosEnsamblados);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel2.setText("Carros");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel7.setText("Bateria");

        javax.swing.GroupLayout JD_MenuSimulacionLayout = new javax.swing.GroupLayout(JD_MenuSimulacion.getContentPane());
        JD_MenuSimulacion.getContentPane().setLayout(JD_MenuSimulacionLayout);
        JD_MenuSimulacionLayout.setHorizontalGroup(
            JD_MenuSimulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JD_MenuSimulacionLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(JD_MenuSimulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JD_MenuSimulacionLayout.createSequentialGroup()
                        .addGroup(JD_MenuSimulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(JD_MenuSimulacionLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(44, 44, 44)
                        .addGroup(JD_MenuSimulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel54))
                .addGap(0, 34, Short.MAX_VALUE))
            .addGroup(JD_MenuSimulacionLayout.createSequentialGroup()
                .addGap(341, 341, 341)
                .addGroup(JD_MenuSimulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(JB_GenerarReporteEnsamblaje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JB_EsamblarBaterias, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JD_MenuSimulacionLayout.setVerticalGroup(
            JD_MenuSimulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JD_MenuSimulacionLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(JD_MenuSimulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JD_MenuSimulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel54)
                .addGap(11, 11, 11)
                .addComponent(JB_EsamblarBaterias, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JB_GenerarReporteEnsamblaje, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        jLabel47.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel47.setText("Bareria seleccionada:");

        JL_BateriaActual.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        jLabel48.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel48.setText("Carro seleccionado:");

        JL_CarroActual.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        PB_Ensamblaje.setString("");
        PB_Ensamblaje.setStringPainted(true);

        JB_IniciarEsamblaje.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        JB_IniciarEsamblaje.setText("Iniciar");
        JB_IniciarEsamblaje.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JB_IniciarEsamblajeMouseClicked(evt);
            }
        });

        JT_SimulacionEnsamblaje.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Pieza ensamblada", "Tiempo que se tardo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(JT_SimulacionEnsamblaje);

        javax.swing.GroupLayout JD_EnsamblajeLayout = new javax.swing.GroupLayout(JD_Ensamblaje.getContentPane());
        JD_Ensamblaje.getContentPane().setLayout(JD_EnsamblajeLayout);
        JD_EnsamblajeLayout.setHorizontalGroup(
            JD_EnsamblajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JD_EnsamblajeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JD_EnsamblajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JD_EnsamblajeLayout.createSequentialGroup()
                        .addComponent(jLabel47)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JL_BateriaActual, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel48)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JL_CarroActual, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(82, 82, 82))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JD_EnsamblajeLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(JD_EnsamblajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 815, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PB_Ensamblaje, javax.swing.GroupLayout.PREFERRED_SIZE, 831, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JD_EnsamblajeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JB_IniciarEsamblaje, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );
        JD_EnsamblajeLayout.setVerticalGroup(
            JD_EnsamblajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JD_EnsamblajeLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(JD_EnsamblajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JD_EnsamblajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(JD_EnsamblajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel48)
                            .addComponent(jLabel47))
                        .addComponent(JL_CarroActual, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JD_EnsamblajeLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(JL_BateriaActual, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(52, 52, 52)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PB_Ensamblaje, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JB_IniciarEsamblaje, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel13.setText("Motor de Combustion");

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel14.setText("Cilidrada del motor: ");

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel15.setText("Consumo de cobustible: ");

        JS_NumCili.setModel(new javax.swing.SpinnerNumberModel(3, 3, 8, 1));

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel16.setText("Numero de cilidros: ");

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel17.setText("Litros/Kilometros");

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel18.setText("en litros");

        JB_AgregarVehiculos.setText("Agregar a Vehiculos");
        JB_AgregarVehiculos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JB_AgregarVehiculosMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout JD_CombustionLayout = new javax.swing.GroupLayout(JD_Combustion.getContentPane());
        JD_Combustion.getContentPane().setLayout(JD_CombustionLayout);
        JD_CombustionLayout.setHorizontalGroup(
            JD_CombustionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JD_CombustionLayout.createSequentialGroup()
                .addGroup(JD_CombustionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JD_CombustionLayout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(jLabel13))
                    .addGroup(JD_CombustionLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(JD_CombustionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel16))
                        .addGap(38, 38, 38)
                        .addGroup(JD_CombustionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JS_NumCili, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(JD_CombustionLayout.createSequentialGroup()
                                .addComponent(JS_Cilidrada, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel18))))
                    .addGroup(JD_CombustionLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel15)
                        .addGap(18, 18, 18)
                        .addComponent(JS_Consumo, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel17))
                    .addGroup(JD_CombustionLayout.createSequentialGroup()
                        .addGap(206, 206, 206)
                        .addComponent(JB_AgregarVehiculos, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(112, Short.MAX_VALUE))
        );
        JD_CombustionLayout.setVerticalGroup(
            JD_CombustionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JD_CombustionLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel13)
                .addGap(36, 36, 36)
                .addGroup(JD_CombustionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(JS_Cilidrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addGap(18, 18, 18)
                .addGroup(JD_CombustionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JS_NumCili, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addGap(19, 19, 19)
                .addGroup(JD_CombustionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(JS_Consumo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addGap(26, 26, 26)
                .addComponent(JB_AgregarVehiculos)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        JS_Cantidad_de_galones.setModel(new javax.swing.SpinnerNumberModel(0.0d, null, null, 1.0d));

        jLabel19.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel19.setText("Cantidad de galones: ");

        jLabel20.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel20.setText("en litros");

        jLabel21.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel21.setText("Motor Hibrido");

        jLabel22.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel22.setText("Capacidad de motor:");

        jLabel23.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel23.setText("Precio inicial: ");

        JB_AgregarVehiculos1.setText("Agregar a Vehiculos");
        JB_AgregarVehiculos1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JB_AgregarVehiculos1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout JD_HibridoLayout = new javax.swing.GroupLayout(JD_Hibrido.getContentPane());
        JD_Hibrido.getContentPane().setLayout(JD_HibridoLayout);
        JD_HibridoLayout.setHorizontalGroup(
            JD_HibridoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JD_HibridoLayout.createSequentialGroup()
                .addGroup(JD_HibridoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JD_HibridoLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(JD_HibridoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22)
                            .addComponent(jLabel19)
                            .addComponent(jLabel23))
                        .addGap(38, 38, 38)
                        .addGroup(JD_HibridoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JS_Cantidad_de_galones, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(JD_HibridoLayout.createSequentialGroup()
                                .addComponent(JS_Capacidad_m, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel20))
                            .addComponent(TF_Precio, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(JD_HibridoLayout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JD_HibridoLayout.createSequentialGroup()
                        .addGap(196, 196, 196)
                        .addComponent(JB_AgregarVehiculos1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(133, Short.MAX_VALUE))
        );
        JD_HibridoLayout.setVerticalGroup(
            JD_HibridoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JD_HibridoLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel21)
                .addGap(36, 36, 36)
                .addGroup(JD_HibridoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(JS_Capacidad_m, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addGap(18, 18, 18)
                .addGroup(JD_HibridoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JS_Cantidad_de_galones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addGap(18, 18, 18)
                .addGroup(JD_HibridoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(TF_Precio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(JB_AgregarVehiculos1)
                .addContainerGap(84, Short.MAX_VALUE))
        );

        jLabel24.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel24.setText("Tiempo de Recarga:");

        JS_NumMotores.setModel(new javax.swing.SpinnerNumberModel());

        jLabel25.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel25.setText("Numero de motores: ");

        JB_AgregarVehiculos2.setText("Agregar a Vehiculos");
        JB_AgregarVehiculos2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JB_AgregarVehiculos2MouseClicked(evt);
            }
        });

        jLabel28.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel28.setText("Motor Electrico");

        jLabel29.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel29.setText("Coeficiente Aerodinamico:");

        javax.swing.GroupLayout JD_ElectricoLayout = new javax.swing.GroupLayout(JD_Electrico.getContentPane());
        JD_Electrico.getContentPane().setLayout(JD_ElectricoLayout);
        JD_ElectricoLayout.setHorizontalGroup(
            JD_ElectricoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JD_ElectricoLayout.createSequentialGroup()
                .addGroup(JD_ElectricoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JD_ElectricoLayout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(jLabel28))
                    .addGroup(JD_ElectricoLayout.createSequentialGroup()
                        .addGap(206, 206, 206)
                        .addComponent(JB_AgregarVehiculos2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JD_ElectricoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(JD_ElectricoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, JD_ElectricoLayout.createSequentialGroup()
                                .addComponent(jLabel24)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(JS_Recarga, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, JD_ElectricoLayout.createSequentialGroup()
                                .addGroup(JD_ElectricoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel29)
                                    .addComponent(jLabel25))
                                .addGap(30, 30, 30)
                                .addGroup(JD_ElectricoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(JS_Coeficiente, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(JS_NumMotores, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(263, Short.MAX_VALUE))
        );
        JD_ElectricoLayout.setVerticalGroup(
            JD_ElectricoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JD_ElectricoLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel28)
                .addGap(36, 36, 36)
                .addGroup(JD_ElectricoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(JS_Coeficiente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(JD_ElectricoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JS_NumMotores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25))
                .addGap(19, 19, 19)
                .addGroup(JD_ElectricoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(JS_Recarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(JB_AgregarVehiculos2)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Salir del Sistema");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Bienvenidos al Sistema");

        JM_AdminCarrosBateria.setText("Admin Vehiculos/ Bateria");

        JMI_CrudVehiculos.setText("Ver Vehiculos");
        JMI_CrudVehiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMI_CrudVehiculosActionPerformed(evt);
            }
        });
        JM_AdminCarrosBateria.add(JMI_CrudVehiculos);

        JMI_CrudBateria.setText("Ver Bateria");
        JMI_CrudBateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMI_CrudBateriaActionPerformed(evt);
            }
        });
        JM_AdminCarrosBateria.add(JMI_CrudBateria);

        jMenuBar1.add(JM_AdminCarrosBateria);

        JM_SimulacionHilo.setText("Simulacion Hilo");

        JMI_SimulacionHilo.setText("Simulacion");
        JMI_SimulacionHilo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMI_SimulacionHiloActionPerformed(evt);
            }
        });
        JM_SimulacionHilo.add(JMI_SimulacionHilo);

        jMenuBar1.add(JM_SimulacionHilo);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(210, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(132, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JMI_CrudVehiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMI_CrudVehiculosActionPerformed
        Administrar_Vehiculos av
                = new Administrar_Vehiculos("./vehiculos.sana");
        av.cargarArchivo();
        DefaultTableModel modelo1 = (DefaultTableModel) JT_ListarVehiculos.getModel();
        modelo1.setNumRows(0);
        JT_ListarVehiculos.setModel(modelo1);
        for (int i = 0; i < av.getListaVehiculos().size(); i++) {
            Object[] o = {av.getListaVehiculos().get(i).getMarca(),
                av.getListaVehiculos().get(i).getVin(),
                av.getListaVehiculos().get(i).getModelo(),
                av.getListaVehiculos().get(i).getCarroceria()};
            modelo1.addRow(o);
        }
        JT_ListarVehiculos.setModel(modelo1);
        CRUDVEHICULO();
    }//GEN-LAST:event_JMI_CrudVehiculosActionPerformed

    private void JMI_CrudBateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMI_CrudBateriaActionPerformed
        // TODO add your handling code here:
        CRUDBATERIA();
    }//GEN-LAST:event_JMI_CrudBateriaActionPerformed

    private void JMI_SimulacionHiloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMI_SimulacionHiloActionPerformed
        SIMULACION();
    }//GEN-LAST:event_JMI_SimulacionHiloActionPerformed

    private void JB_EsamblarBateriasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JB_EsamblarBateriasMouseClicked
        // TODO add your handling code here:
        /*DefaultListModel modelo = (DefaultListModel) JL_ComputadorasEnsamblajes.getModel();
        DefaultListModel modelo2 = (DefaultListModel) JL_TecnicosEnsamblaje.getModel();
        String computadora = ((Computadora) modelo.getElementAt(JL_ComputadorasEnsamblajes.getSelectedIndex())).getSerie();
        String tecnico = ((Tecnico) modelo2.getElementAt(JL_TecnicosEnsamblaje.getSelectedIndex())).getNombre();
        JL_ComputadoraActual.setText(computadora);
        JL_TecnicoActual.setText(tecnico);
        SimulacionEnsamblaje();*/
    }//GEN-LAST:event_JB_EsamblarBateriasMouseClicked

    private void JB_GenerarReporteEnsamblajeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JB_GenerarReporteEnsamblajeMouseClicked
        // TODO add your handling code here:
        //me escuchas????
        /*DefaultTableModel modelo3 = (DefaultTableModel) JT_SimulacionEnsamblaje.getModel();
        for (int i = 0; i < JT_SimulacionEnsamblaje.getRowCount(); i++) {
            Object r = modelo3.getValueAt(i, 0);
            Object r1 = modelo3.getValueAt(i, 1);
            rep += "\nPieza Ensamblada:" + r + " Tiempo: " + r1 + "\n";

        }
        rep += "\n";
        System.out.println(rep);
        JFileChooser jfc = new JFileChooser();
        FileNameExtensionFilter filtro
        = new FileNameExtensionFilter(
            "Archivos de texto", "txt");
        jfc.setFileFilter(filtro);
        int seleccion = jfc.showSaveDialog(this);

        FileOutputStream fw = null;
        ObjectOutputStream bw = null;
        if (seleccion == JFileChooser.APPROVE_OPTION) {
            try {

                File fichero = null;
                if (jfc.getFileFilter().getDescription().equals(
                    "Archivos de texto")) {
                fichero
                = new File(jfc.getSelectedFile().getPath() + ".txt");
            } else {
                fichero = jfc.getSelectedFile();
            }

            fw = new FileOutputStream(fichero);
            bw = new ObjectOutputStream(fw);

            Object f = rep;
            bw.writeObject(f);
            bw.flush();
            //Ya

            JOptionPane.showMessageDialog(JD_MenuEnsamblaje,
                "Archivo guardado exitosamente");

        } catch (Exception e) {
            e.printStackTrace();
        }
        }*/
    }//GEN-LAST:event_JB_GenerarReporteEnsamblajeMouseClicked

    private void JB_IniciarEsamblajeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JB_IniciarEsamblajeMouseClicked
        // TODO add your handling code here:

        /*DefaultListModel modelo = (DefaultListModel) JL_ComputadorasEnsamblajes.getModel();
        DefaultTableModel m = (DefaultTableModel) JT_SimulacionEnsamblaje.getModel();
        DefaultListModel n = (DefaultListModel) JL_TecnicosEnsamblaje.getModel();
        Tecnico t = ((Tecnico) n.getElementAt(JL_TecnicosEnsamblaje.getSelectedIndex()));
        t.setCantidad_computadoras(t.getCantidad_computadoras() + 1);
        Computadora c = ((Computadora) modelo.getElementAt(JL_ComputadorasEnsamblajes.getSelectedIndex()));
        adminBarra ab = new adminBarra(PB_Ensamblaje, c, JT_SimulacionEnsamblaje);
        ab.start();
        ab.Tabla();
        int s;
        if (t.getCantidad_computadoras() < 6) {
            s = 1 + ta.nextInt(100);
            if (s > 0 && s < 31) {
                JOptionPane.showMessageDialog(JD_MenuEnsamblaje, "Ha ocurrido un error de ensamble");
            }//fin del if
        }//fin de la condicion
        else if (t.getCantidad_computadoras() >= 6 && t.getCantidad_computadoras() < 15) {
            s = 1 + ta.nextInt(100);
            if (s > 0 && s < 22) {
                JOptionPane.showMessageDialog(JD_MenuEnsamblaje, "Ha ocurrido un error de ensamble");
            }//fin del if
        }//fin del condicion
        else if (t.getCantidad_computadoras() >= 15 && t.getCantidad_computadoras() < 31) {
            s = 1 + ta.nextInt(100);
            if (s > 0 && s < 13) {
                JOptionPane.showMessageDialog(JD_MenuEnsamblaje, "Ha ocurrido un error de ensamble");
            }
        } else if (t.getCantidad_computadoras() >= 31) {
            s = 1 + ta.nextInt(100);
            if (s > 0 && s < 7) {
                JOptionPane.showMessageDialog(JD_MenuEnsamblaje, "Ha ocurrido un error de ensamble");
            }
        }
        */
    }//GEN-LAST:event_JB_IniciarEsamblajeMouseClicked

    private void JB_BuscarMotorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JB_BuscarMotorMouseClicked
        // TODO add your handling code here:
        if(CB_TipoMotor.getSelectedIndex()!=0){
            int p=CB_TipoMotor.getSelectedIndex();
            switch(p){
                case 1:
                    COMBUSTION();
                break;
                case 2:
                    HIBRIDO();
                break;
                case 3:
                    ELECTRICO();
                break;
            }
        }
    }//GEN-LAST:event_JB_BuscarMotorMouseClicked

    private void JB_AgregarVehiculosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JB_AgregarVehiculosMouseClicked
        // TODO add your handling code here:
        Administrar_Vehiculos av
                = new Administrar_Vehiculos("./vehiculos.sana");
        av.cargarArchivo();
        String t="";
        Object o= CB_TipoCarroce.getSelectedItem();
        t+=o;
        Combustion c= new Combustion((Integer)JS_Cilidrada.getValue(),(Integer)JS_NumCili.getValue(),(Integer)JS_Consumo.getValue(),TF_Marca.getText(),TF_Modelo.getText(),Integer.parseInt(TF_VIN.getText()),t);
        av.getListaVehiculos().add(c);
        av.escribirArchivo();
        DefaultTableModel modelo=(DefaultTableModel)JT_ListarVehiculos.getModel();
        Object[]o1={TF_Marca.getText(),TF_Modelo.getText(),Integer.parseInt(TF_VIN.getText()),t};
        modelo.addRow(o1);
        JT_ListarVehiculos.setModel(modelo);
        JS_Cilidrada.setValue(0);
        JS_NumCili.setValue(3);
        JS_Consumo.setValue(0);
        TF_Marca.setText("");
        TF_Modelo.setText("");
        TF_VIN.setText("");
        CB_TipoCarroce.setSelectedIndex(0);
        CB_TipoMotor.setSelectedIndex(0);
        JD_Combustion.setVisible(false);
    }//GEN-LAST:event_JB_AgregarVehiculosMouseClicked

    private void JB_AgregarVehiculos1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JB_AgregarVehiculos1MouseClicked
        // TODO add your handling code here:
        Administrar_Vehiculos av
                = new Administrar_Vehiculos("./vehiculos.sana");
        av.cargarArchivo();
        String t="";
        Object o= CB_TipoCarroce.getSelectedItem();
        t+=o;
        Hibrido h= new Hibrido((Integer)JS_Capacidad_m.getValue(),(Integer)JS_Cantidad_de_galones.getValue(),Double.parseDouble(TF_Precio.getText()),TF_Marca.getText(),TF_Modelo.getText(),Integer.parseInt(TF_VIN.getText()),t);
        av.getListaVehiculos().add(h);
        av.escribirArchivo();
        DefaultTableModel modelo=(DefaultTableModel)JT_ListarVehiculos.getModel();
        Object[]o1={TF_Marca.getText(),TF_Modelo.getText(),Integer.parseInt(TF_VIN.getText()),t};
        modelo.addRow(o1);
        JT_ListarVehiculos.setModel(modelo);
        JS_Capacidad_m.setValue(0);
        JS_Cantidad_de_galones.setValue(0);
        TF_Precio.setText("");
        TF_Marca.setText("");
        TF_Modelo.setText("");
        TF_VIN.setText("");
        CB_TipoCarroce.setSelectedIndex(0);
        CB_TipoMotor.setSelectedIndex(0);
        JD_Hibrido.setVisible(false);
    }//GEN-LAST:event_JB_AgregarVehiculos1MouseClicked

    private void JB_AgregarVehiculos2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JB_AgregarVehiculos2MouseClicked
        // TODO add your handling code here:
        Administrar_Vehiculos av
                = new Administrar_Vehiculos("./vehiculos.sana");
        av.cargarArchivo();
        String t="";
        Object o= CB_TipoCarroce.getSelectedItem();
        t+=o;
        Electrico h= new Electrico((Integer)JS_Coeficiente.getValue(),(Integer)JS_NumMotores.getValue(),(Integer)JS_Recarga.getValue(),TF_Marca.getText(),TF_Modelo.getText(),Integer.parseInt(TF_VIN.getText()),t);
        av.getListaVehiculos().add(h);
        av.escribirArchivo();
        DefaultTableModel modelo=(DefaultTableModel)JT_ListarVehiculos.getModel();
        Object[]o1={TF_Marca.getText(),TF_Modelo.getText(),Integer.parseInt(TF_VIN.getText()),t};
        modelo.addRow(o1);
        JT_ListarVehiculos.setModel(modelo);
        JS_Coeficiente.setValue(0);
        JS_NumMotores.setValue(0);
        JS_Recarga.setValue(0);
        TF_Marca.setText("");
        TF_Modelo.setText("");
        TF_VIN.setText("");
        CB_TipoCarroce.setSelectedIndex(0);
        CB_TipoMotor.setSelectedIndex(0);
        JD_Electrico.setVisible(false);
    }//GEN-LAST:event_JB_AgregarVehiculos2MouseClicked

    private void JB_ModificarVehiculoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JB_ModificarVehiculoMouseClicked
        // TODO add your handling code here:
         Administrar_Vehiculos av
                = new Administrar_Vehiculos("./vehiculos.sana");
        av.cargarArchivo();
        int p = JT_ListarVehiculos.getSelectedRow();
        if (av.getListaVehiculos().get(p) instanceof Combustion) {
            av.getListaVehiculos().get(p).setVin(Integer.parseInt(JOptionPane.showInputDialog("VIN del Carro: ")));
            av.getListaVehiculos().get(p).setMarca(JOptionPane.showInputDialog("Marca del Carro: "));
            av.getListaVehiculos().get(p).setModelo(JOptionPane.showInputDialog("Modelo del Carro: "));
            av.getListaVehiculos().get(p).setCarroceria(JOptionPane.showInputDialog("Tipo Carroceria del Carro\n"
                    + "[Familiar/SUV/Compacto/Subcompacto/deportivo]: "));
            ((Combustion)av.getListaVehiculos().get(p)).setCilindraje(Integer.parseInt(JOptionPane.showInputDialog("Cilindraje del Motor[en Litros]: ")));
            ((Combustion)av.getListaVehiculos().get(p)).setCant_cilin(Integer.parseInt(JOptionPane.showInputDialog("Cantidad de Cilindros: ")));
            ((Combustion)av.getListaVehiculos().get(p)).setConsumo(Integer.parseInt(JOptionPane.showInputDialog("Cantidad de Conusmo[L/KM]: ")));
        } else if (av.getListaVehiculos().get(p) instanceof Electrico) {
            av.getListaVehiculos().get(p).setVin(Integer.parseInt(JOptionPane.showInputDialog("VIN del Carro: ")));
            av.getListaVehiculos().get(p).setMarca(JOptionPane.showInputDialog("Marca del Carro: "));
            av.getListaVehiculos().get(p).setModelo(JOptionPane.showInputDialog("Modelo del Carro: "));
            av.getListaVehiculos().get(p).setCarroceria(JOptionPane.showInputDialog("Tipo Carroceria del Carro\n"
                    + "[Familiar/SUV/Compacto/Subcompacto/deportivo]: "));
            ((Electrico)av.getListaVehiculos().get(p)).setCoeficiente(Integer.parseInt(JOptionPane.showInputDialog("Coeficiente Aerodinamico: ")));
            ((Electrico)av.getListaVehiculos().get(p)).setCanti_motor(Integer.parseInt(JOptionPane.showInputDialog("Cantidad de Motores: ")));
            ((Electrico)av.getListaVehiculos().get(p)).setTiempo_recarga(Integer.parseInt(JOptionPane.showInputDialog("Tiempo de Recarga: ")));
            
        } else if (av.getListaVehiculos().get(p) instanceof Hibrido) {
            av.getListaVehiculos().get(p).setVin(Integer.parseInt(JOptionPane.showInputDialog("VIN del Carro: ")));
            av.getListaVehiculos().get(p).setMarca(JOptionPane.showInputDialog("Marca del Carro: "));
            av.getListaVehiculos().get(p).setModelo(JOptionPane.showInputDialog("Modelo del Carro: "));
            av.getListaVehiculos().get(p).setCarroceria(JOptionPane.showInputDialog("Tipo Carroceria del Carro\n"
                    + "[Familiar/SUV/Compacto/Subcompacto/deportivo]: "));
            ((Hibrido)av.getListaVehiculos().get(p)).setCantidad_de_galones(Integer.parseInt(JOptionPane.showInputDialog("Cantidad de Galones: ")));
            ((Hibrido)av.getListaVehiculos().get(p)).setCapaci_m(Integer.parseInt(JOptionPane.showInputDialog("Capacidad del Motor: ")));
            ((Hibrido)av.getListaVehiculos().get(p)).setPrecio(Double.parseDouble(JOptionPane.showInputDialog("Precio: ")));
        }//fin de las condiciones
        DefaultTableModel modelo1 = (DefaultTableModel) JT_ListarVehiculos.getModel();
        av.escribirArchivo();
        modelo1.setNumRows(0);
        JT_ListarVehiculos.setModel(modelo1);
        for (int i = 0; i < av.getListaVehiculos().size(); i++) {
            Object[] o = {av.getListaVehiculos().get(i).getMarca(),
                av.getListaVehiculos().get(i).getVin(),
                av.getListaVehiculos().get(i).getModelo(),
                av.getListaVehiculos().get(i).getCarroceria()};
            modelo1.addRow(o);
        }
        JT_ListarVehiculos.setModel(modelo1);
        JOptionPane.showMessageDialog(JD_CRUDVehiculos, "Carro Modficado Exitosamente ");
    }//GEN-LAST:event_JB_ModificarVehiculoMouseClicked

    private void JB_EliminarVehiculosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JB_EliminarVehiculosMouseClicked
        // TODO add your handling code here:
        Administrar_Vehiculos av
                = new Administrar_Vehiculos("./vehiculos.sana");
        av.cargarArchivo();
        int p = JT_ListarVehiculos.getSelectedRow();
        av.getListaVehiculos().remove(p);
        av.escribirArchivo();
        DefaultTableModel modelo1 = (DefaultTableModel) JT_ListarVehiculos.getModel();
        modelo1.removeRow(p);
        JT_ListarVehiculos.setModel(modelo1);
        JOptionPane.showMessageDialog(JD_CRUDVehiculos,"Computadora Eliminada Exitosamente ");
    }//GEN-LAST:event_JB_EliminarVehiculosMouseClicked

    private void JB_BateriaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JB_BateriaMouseClicked
        // TODO add your handling code here:
        Administrar_Bateria ab
                = new Administrar_Bateria("./baterias.sana");
        ab.escribirArchivo();
        String t="";
        Object o= CB_Vehiculo.getSelectedItem();
        t+=o;
        Bateria b= new Bateria(TF_Marca1.getText(),(Integer)JS_Capacidad.getValue(),(Integer)JS_Autonomia.getValue(),(Integer)JS_Modulos.getValue(),(Integer)JS_Carga.getValue(),t,(Integer)JS_Tiempo.getValue());
        ab.getListaBatria().add(b);
        DefaultTableModel modelo =(DefaultTableModel)JT_ListarCarros1.getModel();
        Object[]o1={TF_Marca1.getText(),(Integer)JS_Capacidad.getValue(),t,(Integer)JS_Tiempo.getValue(),(Integer)JS_Autonomia.getValue(),(Integer)JS_Carga.getValue()};
        modelo.addRow(o1);
        JT_ListarCarros1.setModel(modelo);
        ab.escribirArchivo();
        TF_Marca1.setText("");
        JS_Capacidad.setValue(0);
        JS_Autonomia.setValue(0);
        JS_Modulos.setValue(0);
        JS_Carga.setValue(0);
        CB_Vehiculo.setSelectedIndex(0);
        JS_Tiempo.setValue(0);
    }//GEN-LAST:event_JB_BateriaMouseClicked

    private void JB_ModificarCarro1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JB_ModificarCarro1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_JB_ModificarCarro1MouseClicked

    /**
     * @param args the command line arguments
     */
     public void CRUDVEHICULO() {
        JD_CRUDVehiculos.pack();
        JD_CRUDVehiculos.setModal(true);
        JD_CRUDVehiculos.setLocationRelativeTo(this);
        JD_CRUDVehiculos.setVisible(true);
    }
      public void COMBUSTION() {
        JD_Combustion.pack();
        JD_Combustion.setModal(true);
        JD_Combustion.setLocationRelativeTo(this);
        JD_Combustion.setVisible(true);
    }
      public void HIBRIDO() {
        JD_Hibrido.pack();
        JD_Hibrido.setModal(true);
        JD_Hibrido.setLocationRelativeTo(this);
        JD_Hibrido.setVisible(true);
    }
       public void ELECTRICO() {
        JD_Electrico.pack();
        JD_Electrico.setModal(true);
        JD_Electrico.setLocationRelativeTo(this);
        JD_Electrico.setVisible(true);
    }
     public void CRUDBATERIA() {
        JD_CRUDBateria.pack();
        JD_CRUDBateria.setModal(true);
        JD_CRUDBateria.setLocationRelativeTo(this);
        JD_CRUDBateria.setVisible(true);
    }
     public void SIMULACION() {
        JD_MenuSimulacion.pack();
        JD_MenuSimulacion.setModal(true);
        JD_MenuSimulacion.setLocationRelativeTo(this);
        JD_MenuSimulacion.setVisible(true);
    }
     public void ENSAMBLEJE() {
        JD_Ensamblaje.pack();
        JD_Ensamblaje.setModal(true);
        JD_Ensamblaje.setLocationRelativeTo(this);
        JD_Ensamblaje.setVisible(true);
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JF_Examen2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JF_Examen2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JF_Examen2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JF_Examen2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JF_Examen2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CB_TipoCarroce;
    private javax.swing.JComboBox<String> CB_TipoMotor;
    private javax.swing.JComboBox<String> CB_Vehiculo;
    private javax.swing.JButton JB_AgregarVehiculos;
    private javax.swing.JButton JB_AgregarVehiculos1;
    private javax.swing.JButton JB_AgregarVehiculos2;
    private javax.swing.JButton JB_Bateria;
    private javax.swing.JButton JB_BuscarMotor;
    private javax.swing.JButton JB_EliminarCarros1;
    private javax.swing.JButton JB_EliminarVehiculos;
    private javax.swing.JButton JB_EsamblarBaterias;
    private javax.swing.JButton JB_GenerarReporteEnsamblaje;
    private javax.swing.JButton JB_IniciarEsamblaje;
    private javax.swing.JButton JB_ModificarCarro1;
    private javax.swing.JButton JB_ModificarVehiculo;
    private javax.swing.JDialog JD_CRUDBateria;
    private javax.swing.JDialog JD_CRUDVehiculos;
    private javax.swing.JDialog JD_Combustion;
    private javax.swing.JDialog JD_Electrico;
    private javax.swing.JDialog JD_Ensamblaje;
    private javax.swing.JDialog JD_Hibrido;
    private javax.swing.JDialog JD_MenuSimulacion;
    private javax.swing.JLabel JL_BateriaActual;
    private javax.swing.JList<String> JL_BateriaEnsamblaje;
    private javax.swing.JLabel JL_CarroActual;
    private javax.swing.JList<String> JL_CarrosEnsamblados;
    private javax.swing.JMenuItem JMI_CrudBateria;
    private javax.swing.JMenuItem JMI_CrudVehiculos;
    private javax.swing.JMenuItem JMI_SimulacionHilo;
    private javax.swing.JMenu JM_AdminCarrosBateria;
    private javax.swing.JMenu JM_SimulacionHilo;
    private javax.swing.JSpinner JS_Autonomia;
    private javax.swing.JSpinner JS_Cantidad_de_galones;
    private javax.swing.JSpinner JS_Capacidad;
    private javax.swing.JSpinner JS_Capacidad_m;
    private javax.swing.JSpinner JS_Carga;
    private javax.swing.JSpinner JS_Cilidrada;
    private javax.swing.JSpinner JS_Coeficiente;
    private javax.swing.JSpinner JS_Consumo;
    private javax.swing.JSpinner JS_Modulos;
    private javax.swing.JSpinner JS_NumCili;
    private javax.swing.JSpinner JS_NumMotores;
    private javax.swing.JSpinner JS_Recarga;
    private javax.swing.JSpinner JS_Tiempo;
    private javax.swing.JTable JT_ListarCarros1;
    private javax.swing.JTable JT_ListarVehiculos;
    private javax.swing.JTable JT_SimulacionEnsamblaje;
    private javax.swing.JProgressBar PB_Ensamblaje;
    private javax.swing.JTextField TF_Marca;
    private javax.swing.JTextField TF_Marca1;
    private javax.swing.JTextField TF_Modelo;
    private javax.swing.JTextField TF_Precio;
    private javax.swing.JTextField TF_VIN;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    // End of variables declaration//GEN-END:variables
}
